### PR TITLE
create overworld and dungeon maps

### PR DESCRIPTION
**Pull request by cdingm**
all maps are in webp format for less resource usage.
Currently, only the maps for world 1 and world1-dungeon1 exist, all other maps are simply a copy so that the lecturer interface displays a wrong image instead of a `not found` error.

Closes Gamify-IT/issues#230

### CODE REVIEW

**Review by delvh — COMMENTED** [review]
I probably prefer its own directory.
As we will reference this in production, we should choose wisely.
What about `user-manuals/maps/$(lowercase AREA, i.e. world1 or world1-dungeon1)/{raw,minigames,dungeons,npcs}.png`?

**Comment by cdingm** [comment]
> I probably prefer its own directory. As we will reference this in production, we should choose wisely. What about `user-manuals/maps/$(lowercase AREA, i.e. world1 or world1-dungeon1)/{raw,minigames,dungeons,npcs}.png`?

i wasnt sure where to put them, so your suggestion is a good idea

**Review by Gr33ndev — APPROVED** [review]

**Comment by delvh** [comment]
This branch will definitely be **squash merged**.

**Review by delvh — APPROVED** [review]

**Comment by cdingm** [comment]
> This branch will definitely be **squash merged**.

feel free to do that :D

**Pull request merged**
