### PR TITLE
Add class diagrams to the overworld-backend architecture file

### PR DESCRIPTION
**Pull request by Aaron2000119**

### CODE REVIEW

**Comment by cdingm** [comment]
the pictures are not cropped. is it possible to crop so we dont see so much blank space?

**Comment by delvh** [comment]
Also: `kebab-case` for filenames, not `PascalCase`.

**Comment by delvh** [comment]
`dev-manuals/architecture/overworld-backend/assets/overworld-backend-overview.svg`. For when you want to murder someone using a diagram…

**Comment by Aaron2000119** [comment]
overworld-backend-complete
This is the alternativ

**Comment by Aaron2000119** [comment]
This is the alternative
overworld-backend-complete

**Comment by delvh** [comment]
I didn't ask for a genocide…

**Review by cdingm — APPROVED** [review]

**Pull request merged**
