### PR TITLE
ADR: API paths on run-config

### PR DESCRIPTION
**Pull request by madebyTimo**
Approve with **1** for:
- `/api/service/vX/`
    - e. g. `/api/overworld/v1/config/minigame/`

Approve with **2** for:
- `/service/api/vX/`
    - e. g. `/overworld/api/v1/config/minigame/`

Approve with **3** for:
- `/api/vX/service/`
    - e. g. `/api/v1/overworld/config/minigame/`

### CODE REVIEW

**Review by delvh — APPROVED** [review]
2

**Review by Gr33ndev — APPROVED** [review]

**Review by Aaron2000119 — APPROVED** [review]

**Review by maexled — APPROVED** [review]
2

**Review by cdingm — APPROVED** [review]
2

**Review by robojones — APPROVED** [review]
🚒 2 pls

**Comment by delvh** [comment]
Time limit for commenting on this ADR: 80 minutes, until 23:59.

**Comment by delvh** [comment]
Good, no new comments.
Merging now.

**Comment by madebyTimo** [comment]
Ehm we forgot to write down the chosen solution

**Comment by delvh** [comment]
Oops. Follow up PR?

**Pull request merged**
