### PR TITLE
Enhance data model for overworld backend

### PR DESCRIPTION
**Pull request by maexled**
Closes Gamify-IT/issues#98

### CODE REVIEW

**Review by delvh — COMMENTED** [review]
a) The duplicate `theme: WorldTheme` in the `world` component in the class diagram seems unwanted.
b) I think we should also store **which** areas the user unlocked, not only the number of unlocked areas: For example, would a value of `4` indicate that he unlocked the first 4 worlds, or would it indicate that he unlocked the first two worlds and the first two dungeons?
c) Is there a reason not to make **all** IDs `text`?
d) `completed boolean DEFAULT false` in `PlayerTaskStatistic`?

**Comment by maexled** [comment]
> a) The duplicate `theme: WorldTheme` in the `world` component in the class diagram seems unwanted. 
b) I think we should also store **which** areas the user unlocked, not only the number of unlocked areas: For example, would a value of `4` indicate that he unlocked the first 4 worlds, or would it indicate that he unlocked the first two worlds and the first two dungeons? 
c) Is there a reason not to make **all** IDs `text`? 
d) `completed boolean DEFAULT false` in `PlayerTaskStatistic`?

a) Yes, copy-paste mistake
b) unlocked_areas is a FOREIGN KEY that should refer to a list of areas. So it should store the existing area objects referenced by the FOREIGN KEY.
c) what is the advantage of this? The ID's are not required outside of this. I don't see any added value here
d) Yes, but as I know when you leave a boolean blank it is always false, or am I wrong?

**Review by cdingm — APPROVED** [review]

**Comment by delvh** [comment]
> b) unlocked_areas is a FOREIGN KEY that should refer to a list of areas. So it should store the existing area objects referenced by the FOREIGN KEY.
d) Yes, but as I know when you leave a boolean blank it is always false, or am I wrong?

a) :+1: 
b) then please add a note that this is meant as a list of foreign keys and not just the count of unlocked areas
c) I'm fine with both, simply wanted to ask if we wanted to make IDs Strings unified.
d) Unfortunately not. That's Java. In SQL, the default value of a boolean is `NULL`.

**Review by Gr33ndev — APPROVED** [review]

**Comment by delvh** [comment]
@maexled please implement the two suggestions I mentioned. Then we can merge the branch.

**Pull request merged**
