### PR TITLE
Add Component diagram

### PR DESCRIPTION
**Pull request by maexled**
Closes Gamify-IT/issues#55

Created component diagram.

TODO: Exact communication between minigame frontends and minigame backends and overworld frontend and overworld backend

[Component Diagram.png)](https://github.com/Gamify-IT/docs/blob/documentation/component-diagram/dev-manuals/services/component-diagram_(editable-with-drawio).png)

### CODE REVIEW

**Review by delvh — APPROVED** [review]
After verbal discussion with you, I understand and support your solution.

**Comment by delvh** [comment]
For everyone else:
The drawio file is included in the png, for some magic reasons, drawio is able to "revectorize" this png when imported.

**Comment by thechinese** [comment]
Is there a structural difference between the different minigames components? 
Since we don't explicitly consider the exact interfaces here, this would make it way less cluttered

**Comment by LeviUniAcc** [comment]
Moorhuhn Frontend -> Backend, 1st point is fitting the current status. The 2nd point can be removed because the fronted checks if the correct answer was shot or not.

**Comment by madebyTimo** [comment]
> Moorhuhn Frontend -> Backend, 1st point is fitting the current status. The 2nd point can be removed because the fronted checks if the correct answer was shot or not.

Is this the case only today or will it stay the same in the future?
If the correct answer is sent to the frontend before it is choosen by the player the player can cheat very easy. He just has to take a look at the request. Or am I wrong?

**Comment by madebyTimo** [comment]
> Is there a structural difference between the different minigames components? Since we don't explicitly consider the exact interfaces here, this would make it way less cluttered

Till now there are no structural differences between the minigames, only the interfaces itself are diverse at some points.

**Comment by LaviniaStiliadou** [comment]
Where can I find the player details? Like last played game, current played game, favourite game, obtained badges, trials for minigames, game statistics as hours played

**Comment by madebyTimo** [comment]
Question 1 from Daily:
Should we save all data we can get from the minigame runs?

Please vote with 
:+1: for yes
:-1:  for no

**Comment by madebyTimo** [comment]
Question 2 from Daily:
Should we create a lecturer-interface backend to centralize the data flow?

Please vote with 
:+1: for yes
:-1:  for no

**Comment by madebyTimo** [comment]
> true, we could just rename the options from correctAnswer, wrongAnswerOne, wrongAnswerTwo into answerOne, answerTwo... and the answerOne is the correct answer. Not 100% cheatproof but i think its enough, no?

I think that is a bad option. Cause we don't need to be cheat-proof I would rather choose your first option.

**Comment by LeviUniAcc** [comment]
> 

alright

**Review by Gr33ndev — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Review by marlau97 — APPROVED** [review]

**Review by cdingm — APPROVED** [review]

**Review by WuestFlorian — APPROVED** [review]

**Review by LeviUniAcc — APPROVED** [review]

**Comment by delvh** [comment]
"Everyone" approved it, can be merged now.

**Pull request merged**
