### PR TITLE
created UML class diagram for the overworld

### PR DESCRIPTION
**Pull request by maexled**
Closes Gamify-IT/issues#38

Created UML class diagram for the overworld.

~Made a fixed value of 5 Areas instead of 0..5 because the areas will exist in the overworld project but may be deactivated by the lecturer by lecturer-interface (same at the dungeons).~ Attribute active is whether the lecturer has activated the area/dungeon or not. Feel free to discuss.

### CODE REVIEW

**Comment by maexled** [comment]
> a) I think it would be beneficial to add the image of the diagram as well into the repo 
b) `protocols` is not the best place for this, better is perhaps both `user-manuals` or `dev-manuals` (I'm not sure which of the two is more useful, because a lecturer should also know the limitations of the overworld when creating an instance) 
c) Wasn't the variable declaration in UML the other way around (i.e. `-areas` on the other side of the arrow)? 
d) When you add a multiplicity, you also have to give this variable a name. This applies especially to the `1` multiplicities. 
e) ~gameN~**n**ame 
f) What exactly is `gameConfigurationID` supposed to be? 
g) the approach of using the `active` boolean instead of defining the relationship as `0..x` sounds more difficult and less future-proof to implement in the end... I'm in favor of using `0..x` instead, what about you?

a) The image is in the repo, i also linked it as comment from the repo.
b) You are right, dev-manuals would be a better place. The lecturer will see the limitations in the lecturer-interface.
c) You are right, I will fix that.
d) You mean if I have `areas` at the line, I have to add it in the Overworld attributes inside the box? - As I know it should not be necessary.
e) See next answer, in my opinion gameName is more explanatory, or gameType.
f) Cause it is the class diagramm of the overworld, the overworld just needs to know what game and what configuration of the game should be played to finish the task (See also here: https://github.com/Gamify-IT/issues/issues/21#issuecomment-1158829583). So the overworld needs to know with what gameconfiguration it shoud call the microservice for the game.
g) My intention behind this was that the objects in the overworld exists with this fixed value as we said in the last review, it just do not care if the lecturer activated it or not. If we change it in the diagram, it might be not that how we want to implement it.

**Comment by delvh** [comment]
a) Yeah, I somehow missed that? I'm fairly certain I even looked for it, but GitHub said that there is only one file changed?
d) No, I meant for example `-overworld` opposite of `-areas`.
f) Yeah, I can see why the per-minigame-configuration is needed
e+f) however, I still don't think the `game`-prefix is needed
g) I have no problem if you get it implemented like the current approach in the end. However, I just mentally tried to implement it, and I think it is easier to implement ( -> less edgecases, better code quality) by using a list that is only filled until it contains `x` elements rather than hardcoding all `x` variables. That's why I proposed the `0..x` over the `x` multiplicity.

**Comment by maexled** [comment]
> a) Yeah, I somehow missed that? I'm fairly certain I even looked for it, but GitHub said that there is only one file changed? However, now I can see it. 
d) No, I meant for example `-overworld` opposite of `-areas`. f) Yeah, I can see why the per-minigame-configuration is needed e+f) however, I still don't think the `game`-prefix is needed 
g) I have no problem if you get it implemented like the current approach in the end. However, I just mentally tried to implement it, and I think it is easier to implement ( -> less edgecases, better code quality) by using a list that is only filled until it contains `x` elements rather than hardcoding all `x` variables. That's why I proposed the `0..x` over the `x` multiplicity.

e+f) ok, I get your point
g) ok, I also get it. When our current sprint goal is only 1-2 areas we can not finish 5. But for now, I will put 0..x to 0..5 and 0..4 as we mentioned it in the las review.

**Review by cdingm — CHANGES_REQUESTED** [review]
looks good, but there is a typo in the two filenames "digram" instead of diagram

**Review by cdingm — APPROVED** [review]

**Review by delvh — APPROVED** [review]

**Review by Gr33ndev — APPROVED** [review]

**Review by marlau97 — APPROVED** [review]

**Comment by maexled** [comment]
got approval from uwe

**Pull request merged**
