### PR TITLE
improve database model

### PR DESCRIPTION
**Pull request by madebyTimo**
improved database model according to result of discussion with supervisor and following internal discussion

closes https://github.com/Gamify-IT/issues/issues/98

### CODE REVIEW

**Review by delvh — COMMENTED** [review]
The two uppermost notes are no longer targeting the correct position

**Comment by maexled** [comment]
grafik
Where goes the arrow from the Dungeon? To Lecture? If yes, how do you know which dungeon belongs to which world?

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
By the way, we forgot the NPC role.

**Review by robojones — APPROVED** [review]
🍵

**Review by delvh — CHANGES_REQUESTED** [review]
Blocking until you incorporate the feedback from the supervisors.

**Comment by madebyTimo** [comment]
Has anyone an idea of a better name for `Playerstatistic`?

I think `PlayerProgress` isn't suitable because it is much more then progress

**Comment by delvh** [comment]
`PlayerProgressLog`?

**Comment by madebyTimo** [comment]
> `PlayerProgressLog`?
That is in my opinion more incomprehensible then `PlayerStatistic`. I think `Progress` is misplaced because we not only save progress, but all information about the player and progress is only a part of that. Also `Log` refers to much to the Log tables on the right

**Comment by maexled** [comment]
@Aaron2000119 and I figured out while implementing the player statistic stuff in the backend that the lecture can change _game_ and _configuration_id_ of a `MinigameTask`. That we can find the game logs in the minigame backends we should add _game_ and _configuration_id_ in `PlayerTaskActionLog`

**Comment by madebyTimo** [comment]
> @Aaron2000119 and I figured out while implementing the player statistic stuff in the backend that the lecture can change _game_ and _configuration_id_ of a `MinigameTask`. That we can find the game logs in the minigame backends we should add _game_ and _configuration_id_ in `PlayerTaskActionLog`

I see what you meen but is this really a good idea? The `PlayerTaskActionLog` is still connected to the same `MinigameTask`.

**Comment by madebyTimo** [comment]
Ok nvm I got it. We need it when we want to fetch minigame-specific statistics from the minigame backend but the minigame changed in between. The points still correspond to the same `MinigameTask` but the statistics are saved at the old minigame-configuration

**Comment by madebyTimo** [comment]
> Shouldn't there be an arrow between TaskStatistic and Task?
> If diagrams get messy with too many arrows split them up in different views

https://github.com/Gamify-IT/issues/issues/98#issuecomment-1191831064
https://github.com/Gamify-IT/issues/issues/98#issuecomment-1193572193

I now added the 2 arrows from `PlayerTaskStatistic` to `MinigameTask` and from `PlayerNPCStatistic` to `NPC`. I left out the arrows from mostly each entity to `Lecture` because this will lead to pure chaos. I also don't know how to split up the diagram to prevent this. If you have any suggestion **please comment**. Otherwise I will take the actual solution

**Comment by delvh** [comment]
What we could do is separate the diagrams into two separate ones:
One diagram could be the statistics, and the other the actual areas and data.

**Comment by madebyTimo** [comment]
After a discussion with @maexled, @WuestFlorian, and @Aaron2000119 about the overworld-backend interface we determined that it is better to use indices and not our locationId format

**Comment by madebyTimo** [comment]
> What we could do is separate the diagrams into two separate ones: One diagram could be the statistics, and the other the actual areas and data.

actually our diagram is almost splitted into these parts. The lower part conttains the statistics and the upper part contains the rest.

I think I will try to add the missing arrows and bundle them at the edges

**Comment by madebyTimo** [comment]
I now added all llecture arrows and I think it is ok cause they are bundled and therefore easy identifiable and don't distract very much

**Review by delvh — APPROVED** [review]
I absolutely **hate** the new arrows, but as this should be merged today, I'll allow it.
So we haven't found a new name for the `PlayerStatistic`? Welp, will be an interesting review...

**Comment by madebyTimo** [comment]
No, we think there is no better name for `PlayerStatistic`.

What is so bad at the new arrows? In a splitted diagram they won't be better

**Comment by delvh** [comment]
Apart from making the diagram bloated I don't have a problem with the arrows.

**Pull request merged**
