### PR TITLE
Draw sequence diagram

### PR DESCRIPTION
**Pull request by madebyTimo**
Closes Gamify-IT/issues#70

Please review and comment if something is wrong or missing

[.png?raw=true)](https://github.com/Gamify-IT/docs/blob/documentation/sequenz-diagram/dev-manuals/services/sequence-diagram_(editable-with-drawio).png)

### CODE REVIEW

**Review by Gr33ndev — APPROVED** [review]

**Comment by LeviUniAcc** [comment]
how does the backend know the configuration for the minigame with the authorization cookie? i thought the cookie is only for the authorization!

**Comment by delvh** [comment]
From the top down:

1. According to my (limited) knowledge of sequence diagrams, the two `return cookie` instructions at the beginning can be omitted, resulting in the extra lifeline-part being obsolete as well.
2. @LeviUniAcc if I understand the `configuration` part correctly, it is not the one you're thinking about: You're thinking about the global configuration, right? But in this case, it seems to be the player-specific one.
3. `return <x>` should always be able to be deleted. You don't mention explicit return values in a sequence diagram. Arrows that only reference their own lifeline then can be deleted as well. 
4. `load configurati`~~i~~`on`
5. Why can't calls end on the same lifeline?
6. Perhaps, when the player progress is sent to the `Overworld Backend`, there should also be an (asynchronous) call from the `Bugfinder Backend` to itself to update the player stats as well (even if it isn't needed exactly for the Bugfinder, as it is used as an example on how all minigame backends should behave)

**Comment by LeviUniAcc** [comment]
> From the top down:
> 
>     1. According to my (limited) knowledge of sequence diagrams, the two `return cookie` instructions at the beginning can be omitted, resulting in the extra lifeline-part being obsolete as well.
> 
>     2. @LeviUniAcc if I understand the `configuration` part correctly, it is not the one you're thinking about: You're thinking about the global configuration, right? But in this case, it seems to be the player-specific one.
> 
>     3. `return <x>` should always be able to be deleted. You don't mention explicit return values in a sequence diagram. Arrows that only reference their own lifeline then without any text can be deleted as well.
> 
>     4. `load configurati`~i~`on`
> 
>     5. Why can't calls end on the same lifeline?
> 
>     6. Perhaps, when the player progress is sent to the `Overworld Backend`, there should also be an (asynchronous) call from the `Bugfinder Backend` to itself to update the player stats as well (even if it isn't needed exactly for the Bugfinder, as it is used as an example on how all minigame backends should behave)

ehm i dont know what you mean. 2 informations are relevant. 1. player specific. 2. overwrold specific. the overworld specific informations are not  inside the cookie, no? but if not where does the backend get these informations from? i dont find it in the sequenze diagram.

**Comment by LeviUniAcc** [comment]
i thought that is one of the MAIN points of this diagramm, the rest is kinda obvious imo

**Review by LeviUniAcc — APPROVED** [review]

**Comment by madebyTimo** [comment]
To clarify the call from the Overworld Frontend to the Overworld Backend.
The Overworld Frontend sends a request to get the configuration from the overworld backend with the cookie attached. Then the backend identifies the user with the cookie and sends the overall and user specific configuration back to the frontend.

**Comment by madebyTimo** [comment]
I think we leave the return values in the diagram till we surely know if they necessary.

**Comment by madebyTimo** [comment]
> Why can't calls end on the same lifeline?
I think because this is UML

**Review by cdingm — CHANGES_REQUESTED** [review]
could you please rename the file to sequence-diagram instead of sequenz :D

**Review by cdingm — APPROVED** [review]

**Review by marlau97 — APPROVED** [review]

**Comment by madebyTimo** [comment]
Yes that's still on my Todo-List. I will add it this evening

**Comment by madebyTimo** [comment]
I specified the forwarding of the minigame configuration id like we discussed it and added the save of game runs in the minigame backend
grafik
grafik

**Review by delvh — APPROVED** [review]

**Comment by delvh** [comment]
It's after the deadline, no new reviews are present.
Let's get it finally merged.

**Pull request merged**
