### PR TITLE
Add files on how to reinstall SonarQube

### PR DESCRIPTION
**Pull request by Gr33ndev**
Gamify-IT/issues#58

### CODE REVIEW

**Review by madebyTimo — COMMENTED** [review]
good work overall, but some things can be enhanced

**Comment by madebyTimo** [comment]
Is there also a reverse-proxy configuration to access sonarqube? With this configuration it only runs at port 9000, isn't it?

**Comment by Gr33ndev** [comment]
The reverse proxy from the first installation still exists unchanged

**Comment by madebyTimo** [comment]
what is about the suggestions from the last review?

**Pull request merged**
